# Generated by Django 5.2.8 on 2025-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userPost',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='media')),
                ('Caption', models.CharField(max_length=255)),
            ],
        ),
    ]
